default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: customer-api_development

test:
  <<: *default
  database: customer-api_test

production:
  <<: *default
  database: customer-api_production
  username: customer-api
  password: <%= ENV['CUSTOMER-API_DATABASE_PASSWORD'] %>
